version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vvaxcoder_hbar
    environment:
      POSTGRES_USER: vvaxcoder
      POSTGRES_PASSWORD: WLgJURYhl3
      POSTGRES_DB: evercode_hbar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - evercode_hbar

volumes:
  postgres_data:

networks:
  evercode_hbar:
    driver: bridge
