version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vvaxcoder_hbar
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - evercode_hbar

volumes:
  postgres_data:

networks:
  evercode_hbar:
    driver: bridge
